### PR TITLE
IMDSv2 attempt should IMDSv1 fail

### PR DESCRIPTION
**Pull request by jmt-lab**
This isn't the prettiest way to do this, but I've added logic so that if IMDSv1 fail on bootup it will then install curl (cause i wasn't able to find a way to do PUT requests with fetch cause i'm a newb), then use curl to use IMDSv2 to get userdata and setup the ssh key. 

I am okay if changes are required, going to test this with our internal amis (basically swap the existing scripts for these in that ami)

### CODE REVIEW

**Comment by cperciva** [comment]
A few suggestions:

1. Rather than duplicating code, let's have a /usr/local/bin/imds_get script.  This will also make things easier when I make an IMDSv2-compatible utility using libfetch.
2. Don't install curl from the script; instead, check if it's available, and preinstall it onto your AMIs.
3. Is there a reason to fetch the SSH key from /latest/ rather than /1.0/ ?

**Comment by jmt-lab** [comment]
1. How bout we do a middle run here, while i don't know your opinion on golang, (me i'm okay with it, i prefer rust but golang makes crosscompiling really easy, i can write in rust if you'd prefer then use an ec2 instance to build binary). Why don't i write a imds_get program that handles imdsv1/v2 
2. No curl no longer needed with imds_get program above
3. I was simply following the IMDS documentation, i'm not sure if there is a benefit, but latest is usually what is suggested

**Comment by cperciva** [comment]
I'm inclined to make use of FreeBSD's libfetch (just from the perspective of "reusing existing code is good") -- I'm not sure how easy it is to use that from golang or rust though?  Also last I checked FreeBSD didn't support golang on all platforms; arguably we only care about amd64 and arm64, but I'd still prefer to use C for the sake of portability.

**Comment by jmt-lab** [comment]
Yeah i do get that, calling libfetch from Rust would be fairly simple to do however, the nice thing about the tool i've written up is that it'll work on any platform, any os. I'm planning to open it up and then adjust the scripts to install it and use it. However the bigger blocker for IMDSv2 enablement on FreeBSD is nothing from me or you, ...the aws cli V2 which is required for imdsv2 is not distributed by the aws cli team (I am engaging them about this as we have decided that we need to support freebsd better)

**Comment by cperciva** [comment]
Assuming your tool doesn't have problematic dependencies, I'd be very happy to package it up for FreeBSD and make `ec2-scripts` depend on it.  (I think that's better than including it in `ec2-scripts` directly, since some of this code gets reused in environments other than FreeBSD+EC2.)

**Comment by jmt-lab** [comment]
I have started the official approval process to get Amazon to let me publish the tool as OpenSource its a small 1 file tool so it shouldn't be any problem. It only really depends on two rust crates:
 async-std and reqwest, i've also configured reqwest to use the Rusttls build so openssl isn't needed (though as you know cause amazon is uh..."special" imds doesn't even use https so whatever) I'll link you the project once i get it out then i can PR the changes to ec2-scripts to use it and we can figure out the depend thing

**Comment by cperciva** [comment]
Sounds good, thanks!

**Comment by jmt-lab** [comment]
I finally was able to publish the tool here: https://github.com/aws/aws-ec2-imdsv2-get  I will send an invite for you to collaborate on it soon

**Comment by jmt-lab** [comment]
I've attached some precompiled binaries to the 1.0 release in the repo if needed, otherwise you should be able to potentially fork and submit PR against i think

**Comment by cperciva** [comment]
Awesome.  I'll take a look and get it packaged up for FreeBSD when I get a chance.

**Comment by cperciva** [comment]
Fixed in e7bb2fcb11fb04f3b245b7bd3c073aee585379f1

**Pull request closed without merging**
